name: build-docker-image
on:
  release:
    types: [published]
jobs:
  build-renderer-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install node/npm and place in path
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: binaries to build in different arch
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64,arm

      - name: setup docker to build differnt arch
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: install deps
        run: npm install

      - name: compile ts
        run: npm run build

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
